from . import crm_lead
from . import crm_team
from . import res_partner
from . import sale_order
from . import event_category
from . import event
from . import event_question
from . import event_registration_answer
from . import website
