{
    'name': 'CRM Real-Time Notifications',
    'version': '19.0.1.0.2',
    'category': 'Sales/CRM',
    'summary': 'Odoo 19 CRM communication badges, per-user unread counters and live browser notifications',
    'description': 'CRM Sales Communication Guard',
    'author': 'GreenMethod',
    'website': '',
    'license': 'LGPL-3',
    'price': 49,
    'currency': 'EUR',
    'depends': ['crm', 'mail', 'bus', 'web'],
    'data': ['security/crm_sales_guard_security.xml', 'security/ir.model.access.csv', 'views/crm_lead_kanban_views.xml', 'views/crm_lead_sales_guard_views.xml'],
    'assets': {'web.assets_backend': ['crm_sales_communication_guard_19/static/src/js/crm_sales_guard_notification_service.js', 'crm_sales_communication_guard_19/static/src/js/crm_sales_guard_systray.js', 'crm_sales_communication_guard_19/static/src/xml/crm_sales_guard_systray.xml', 'crm_sales_communication_guard_19/static/src/scss/crm_sales_guard.scss']},
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'application': True,
    'auto_install': False,
    'images': ['static/description/banner.png', 'static/description/screenshot1.png', 'static/description/screenshot2.png', 'static/description/screenshot3.png'],
}
